name: Build Release

on: 
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "package.json"

permissions:
  contents: write

jobs:
  build:
    if: ${{ github.event.before != '0000000000000000000000000000000000000000' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          submodules: true

      - name: Packaging
        id: packager
        uses: "docker://ghcr.io/rerigferl/vpm-packager:latest"
        with:
          args: "-z -u"
          
      - name: Make Release
        if: ${{ steps.packager.outputs.package-version != '0.0.0' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.packager.outputs.package-version }}
          prerelease: ${{ contains(steps.packager.outputs.package-version, '-') }}
          files: |
            ${{steps.packager.outputs.zip-path}}
            ${{steps.packager.outputs.unitypackage-path}}
            ${{steps.packager.outputs.manifest-path}}
          
         
